

ID_CLIENT = 'ID_CLIENT'
ORIGINE_LEAD = 'ORIGINE_LEAD'
SOURCE_LEAD = 'SOURCE_LEAD'
NIVEAU_LEAD = 'NIVEAU_LEAD'
QUALITE_LEAD = 'QUALITE_LEAD'
CONTACT_PAR_MAIL = 'CONTACT_PAR_MAIL'
CONTACT_PAR_TELEPHONE = 'CONTACT_PAR_TELEPHONE'
STATUT_ACTUEL = 'STATUT_ACTUEL'
CONVERTI = 'CONVERTI'
NB_VISITES = 'NB_VISITES'
DUREE_SUR_SITEWEB = 'DUREE_SUR_SITEWEB'
NB_PAGES_VUES_PAR_VISITE = 'NB_PAGES_VUES_PAR_VISITE'
DERNIERE_ACTIVITE = 'DERNIERE_ACTIVITE'
DERNIERE_ACTIVITE_NOTABLE = 'DERNIERE_ACTIVITE_NOTABLE'
PAYS = 'PAYS'
VILLE = 'VILLE'
SPECIALISATION = 'SPECIALISATION'
TAGS = 'TAGS'
INDEX_ACTIVITE = 'INDEX_ACTIVITE'
INDEX_PROFIL = 'INDEX_PROFIL'
SCORE_ACTIVITE = 'SCORE_ACTIVITE'
SCORE_PROFIL = 'SCORE_PROFIL'
ANNONCE_VUE = 'ANNONCE_VUE'
MAGAZINE = 'MAGAZINE'
ARTICLE_JOURNAL = 'ARTICLE_JOURNAL'
FORUM = 'FORUM'
JOURNAUX = 'JOURNAUX'
PUB_DIGITALE = 'PUB_DIGITALE'
RECOMMANDATION = 'RECOMMANDATION'
COMMENT_ENTENDU_PARLER = 'Comment avez-vous entendu parler de nous ?'
SOUHAITE_RECEVOIR_INFOS = 'Souhaites-tu recevoir plus d\'infos sur notre cours ?'
SOUHAITE_RECEVOIR_MAJ = 'Souhaites-tu recevoir des mises à jour sur nos programmes ?'
SOUHAITE_RECEVOIR_MSG = 'Souhaites-tu recevoir des mises à jour par message privé ?'
SOUHAITE_PAYER_CHEQUE = 'Souhaites-tu payer par chèque ?'
SOUHAITE_LIVRE_BLANC = 'Souhaites-tu recevoir une copie de notre livre blanc ?'

FEATURES = [
            ID_CLIENT,
            ORIGINE_LEAD,
            SOURCE_LEAD,
            NIVEAU_LEAD,
            QUALITE_LEAD,
            CONTACT_PAR_MAIL,
            CONTACT_PAR_TELEPHONE,
            STATUT_ACTUEL,
            NB_VISITES,
            DUREE_SUR_SITEWEB,
            NB_PAGES_VUES_PAR_VISITE,
            DERNIERE_ACTIVITE,
            DERNIERE_ACTIVITE_NOTABLE,
            PAYS,
            VILLE,
            SPECIALISATION,
            TAGS,
            INDEX_ACTIVITE,
            INDEX_PROFIL,
            SCORE_ACTIVITE,
            SCORE_PROFIL,
            ANNONCE_VUE,
            MAGAZINE,
            ARTICLE_JOURNAL,
            FORUM,
            JOURNAUX,
            PUB_DIGITALE,
            RECOMMANDATION,
            COMMENT_ENTENDU_PARLER,
            SOUHAITE_RECEVOIR_INFOS,
            SOUHAITE_RECEVOIR_MAJ,
            SOUHAITE_RECEVOIR_MSG,
            SOUHAITE_PAYER_CHEQUE,
            SOUHAITE_LIVRE_BLANC
            ]

LABEL = CONVERTI
